#!/bin/bash
# This script installs Ansible, Nginx, stress tool, Git and clones a GitHub repo.
# Recommended for t2.micro. For t3.micro, network interface may differ (e.g., ens5).

set -e  # Exit on error

# Update package list
sudo apt-get update -y

# Install necessary packages
sudo apt-get install -y software-properties-common python3-apt git nginx stress

# Add Ansible PPA and install Ansible
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y ansible

# Clone the GitHub repository
sudo git clone https://github.com/salokm77/auto-scaling.git /myrepo

echo "Provisioning completed successfully!"


######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook /myrepo/playbook.yaml

######GIVE BELOW IN THE CUSTOM DATA OF AZURE VMSSS################################
#cloud-config
package_upgrade: true
packages:
  - jq

runcmd:
  - ansible-playbook /myrepo/playbook.yaml
